### ISSUE TITLE
Integrate checking with Syntastic

### ISSUE THREAD

**Issue by blueyed** [MarcWeber/vim-addon-nix#4]
I think it would be useful to have a checker for [Syntastic](https://github.com/scrooloose/syntastic).

Have you done anything in this regard by any chance?  Otherwise I'll give it a shot (and will submit a PR for Syntastic).

**Comment by MarcWeber** [comment]
I forked it: github.com/MarcWeber/vim-addon-syntax-checker because syntastic mixes syntax checking and running interpreters - one is side effect free, the other not. I considered that to be bad style. But you're right, its not that clear where such code should be put - I felt its very useful to know after :w that there are no syntax errors that I had to include it. Whether you get live updates while typing or not was not important to me.Thus putting this code into vim-addon-nix could be a compromise because supporting syntastic is no option for me and moving the code to vim-addon-syntax-checker would be overkill for most people like you. If you think differently reopen
